### ISSUE TITLE
404

### ISSUE THREAD

**Issue by ixnur** [djangoogreniyorum/djangoogreniyorum.github.io#21]
Howdy! So, I stumbled upon this Django tutorial site, and let me tell ya, a bunch of links, especially this one, are playing hide and seek with a 404 error. Now, ain't that something? It's like a wild west of broken links. Come on, folks! Gotta fix these glitches, or we're stuck in a tumbleweed of confusion. Get your act together and make it smooth, ya hear?

**Comment by volkantash** [comment]
Selam. Yıllar önce kendimi geliştirmek ve Türkçe bilenlere yardımcı olabilmek amacı ile yaptığım bir çalışmaydı. Belki Django 5.0 için kolları sıvayabiliriz. Türkçe öğrenmek isteyen Django bilen kişiler belki bu konuya daha çok ilgi duyar ve bir yerlere taşır. Dememin özü şu: "Çok kişi gerekiyor tek başıma yetemem."

İngilizce / English
> Hi. It was a project I did years ago to improve myself and help those who speak Turkish. Maybe we can roll up our sleeves for Django 5.0. People who know Django and want to learn Turkish may be more interested in this subject and take it somewhere. The essence of what I say is this: "It takes many people, I can't do it alone."

**Comment by ixnur** [comment]
Hey buddy, your thought process is awesome! Thinkin' 'bout others is a real fine gesture. Wish them other self-absorbed devs were more like you; the world'd be a darn great place, ya know?

**Comment by ixnur** [comment]
türkiyenin en türkçe takıntılı adamınada ingilizceyi benden başkası yazamazdı :+1: 

şaka bir yana dostum bu gayretinden ötürü seni tebrik eder başarılarının devamını dilerim python konusunda yardımım olucaksa seve seve elimi taşın altına atarım 

türkçeye olan hayranlığın için ayrıca teşekkürler ...

**Comment by ixnur** [comment]
CodeWizardette @ proton.me lâkin münâsebetimiz iyi ola. tez katibime yazasun.

**Comment by volkantash** [comment]
> CodeWizardette @ proton.me lâkin münâsebetimiz iyi ola. tez katibime yazasun.

Ürkütücü.
