### ISSUE TITLE
Terimler Sözlüğü

### ISSUE THREAD

**Issue by MarlonJD** [djangoogreniyorum/djangoogreniyorum.github.io#4]
Çevirinin yapıldığı sayfanın altına yazılımla özdeşleşmiş çoğu kelimenin nasıl çevrildiğini not düşersek daha isabetli bir çeviri ortaya çıkabilir ne dersiniz?

**Comment by volkantash** [comment]
Konuyla ilgileneceğiz.

**Comment by volkantash** [comment]
https://djangoogreniyorum.github.io/terimler/genel.html
https://djangoogreniyorum.github.io/terimler/teknik.html

şimdilik bu dosyalarda terimleri yansıtacağız. Belgeleri yeniden derlerken terimlere bağ vererek bu dosyalara yönlendirme yapılacaktır.

**Comment by MarlonJD** [comment]
Süper oluyor güzel planlamışsınız çok başarılı bir proje olacak gibi duruyor bitince

**Comment by volkantash** [comment]
Alt yapıyı geliştirmek ve yeniden düzenlemek üzerinde çalışmalar yaptık. Ana menüde "diğer" içinde bulunan yazarlar için bölümünü okuyunuz.
